### ISSUE TITLE
no data since 30.11.24 and login not possible

### ISSUE THREAD

**Issue by wceleda** [DarwinsBuddy/WienerNetzeSmartmeter#286] opened 2024-12-05 07:19 UTC
from the log after restart ha:

Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:728
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 08:13:16 (1 Vorkommnisse)
Zuletzt protokolliert: 08:13:16

wnsm: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/wnsm/wnsm_sensor.py", line 88, in async_update
    await async_smartmeter.login()
  File "/config/custom_components/wnsm/AsyncSmartmeter.py", line 24, in login
    return await self.hass.async_add_executor_job(self.smartmeter.login)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 157, in login
    code = self.credentials_login(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 104, in credentials_login
    raise SmartmeterLoginError("Login failed. Check username/password.")
custom_components.wnsm.api.errors.SmartmeterLoginError: Login failed. Check username/password.

**Comment by DarwinsBuddy** [comment] 2024-12-05 11:47
how many smartmeters do you have in your account?

**Comment by opb1978** [comment] 2024-12-06 10:57
I have a similar problem here: 

Running version 1.7.0, only one smart meters:

Logger: custom_components.wnsm.config_flow
Source: custom_components/wnsm/config_flow.py:50
integration: WienerNetzeSmartmeter ([documentation](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter), [issues](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues))
First occurred: 11:53:10 (1 occurrences)
Last logged: 11:53:10

Login failed. Check username/password.
Traceback (most recent call last):
  File "/config/custom_components/wnsm/config_flow.py", line 50, in async_step_user
    zps = await self.validate_auth(
          ^^^^^^^^^^^^^^^^^^^^^^^^^
        user_input[CONF_USERNAME], user_input[CONF_PASSWORD]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/wnsm/config_flow.py", line 34, in validate_auth
    await self.hass.async_add_executor_job(smartmeter.login)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wnsm/api/client.py", line 157, in login
    code = self.credentials_login(url)
  File "/config/custom_components/wnsm/api/client.py", line 104, in credentials_login
    raise SmartmeterLoginError("Login failed. Check username/password.")
custom_components.wnsm.api.errors.SmartmeterLoginError: Login failed. Check username/password.

**Comment by DarwinsBuddy** [comment] 2024-12-06 11:17
Can you both log into your Wiener Netze smart Meter Account online? are you getting presented a capture?

**Comment by l3rdy** [comment] 2024-12-06 22:36
> Can you both log into your Wiener Netze smart Meter Account online? are you getting presented a capture?

I tried to log in to the smartmeter online Account 
https://smartmeter-web.wienernetze.at/ is not available due to maintenance… so this might not help 😅

**Comment by DarwinsBuddy** [comment] 2024-12-07 15:04
duplicate of #288

**Comment by DarwinsBuddy** [comment] 2024-12-07 15:05
@wceleda did you check the FAQs?

**Closed by DarwinsBuddy** 2024-12-07 15:04 UTC
