### ISSUE TITLE
After upgrading to 1.5.4, there is a wrong peak consumption between 0:00 and 1:00 every

### ISSUE THREAD

**Issue by MaxRower** [DarwinsBuddy/WienerNetzeSmartmeter#273] opened 2024-11-12 21:59 UTC
Updated to 1.5.4, since there was no data for the last days, but something is still wrong.
![Screenshot_20241112-225811_Trebuchet~(1)](https://github.com/user-attachments/assets/f3fcc32a-5620-4ef7-a476-6b8337a8033a)
Same problem at two different locations.

**Comment by wceleda** [comment] 2024-11-13 06:14
yep here the same issue:

<img width="1438" alt="grafik" src="https://github.com/user-attachments/assets/6adb179b-d7b6-400a-b44c-de8c6b1f28e8">

**Comment by reox** [comment] 2024-11-13 07:23
Some observed that also during testing of the PR... This behaviour should be gone for the next import - however the old data stays :/ I guess the only way to fix it is to remove the integration, delete all data and start over (unless someone finds a way to fix the statistics)

**Comment by gugaua** [comment] 2024-11-13 09:05
same here, after upgrading to 1.5.4, for every missing day of statistics there is a high spike between 00:00 and 01:00 like in screenshots above.

It would be great to fix it somehow

**Comment by stprograms** [comment] 2024-11-13 09:41
For info:
I had the same problem after upgrading.
After deleting the integration and removing the statistic sensor, I added the integration again and the energy dashboard shows the data correct now.

**Comment by papedo79** [comment] 2024-11-13 09:48
i just removed the spikes from the statistics of 4 or 5 days, and it is working correctly since 2 days.  just use the developer tools - statistics - to delete those wrong entries from the statistics sensor.

**Comment by gugaua** [comment] 2024-11-13 09:57
> i just removed the spikes from the statistics of 4 or 5 days, and it is working correctly since 2 days. just use the developer tools - statistics - to delete those wrong entries from the statistics sensor.

Thank you very much for this input, I didn´t know this option exists, I just checked via https://smartmeter-web.wienernetze.at/verbrauchsdaten/grafische-darstellung the actual reading and changed it to the correct value in developer tools - statistics now everything is fine again

**Comment by reox** [comment] 2024-11-13 10:01
> i just removed the spikes from the statistics of 4 or 5 days, and it is working correctly since 2 days. just use the developer tools - statistics - to delete those wrong entries from the statistics sensor.

ah yes, that is possible! Thanks!

Would be still interesting to know the reason for that and to be able to reproduce...

**Comment by tschoerk** [comment] 2024-11-13 10:12
In the FAQs there is also an instruction to completly start over with fresh data #19 **How can I start over with a fresh data import?**

> > i just removed the spikes from the statistics of 4 or 5 days, and it is working correctly since 2 days. just use the developer tools - statistics - to delete those wrong entries from the statistics sensor.
> 
> ah yes, that is possible! Thanks!
> 
> Would be still interesting to know the reason for that and to be able to reproduce...

We could stop updating via some code commenting for a couple of days and then reactivate it again with debugging on to see exactly what is returned. Maybe that's how we could reproduce the bug.

It seems to be a problem when more than 24 hours are updated via bewegungsdaten and I think then the total_consumption is somehow set to the midnight timestamp. Can't figure it out though without some debugging data.

**Comment by MaxRower** [comment] 2024-11-13 10:32
> It seems to be a problem when more than 24 hours are updated via bewegungsdaten and I think then the total_consumption is somehow set to the midnight timestamp.
If you uninstall the integration and start over, then this should happen again, in your optinion? Apperently, it does not.

**Comment by tschoerk** [comment] 2024-11-13 10:42
> > It seems to be a problem when more than 24 hours are updated via bewegungsdaten and I think then the total_consumption is somehow set to the midnight timestamp.
> 
> If you uninstall the integration and start over, then this should happen again, in your optinion? Apperently, it does not.

I think it happens again if there's already data present and the update is delayed for a couple days.

There are two different processes: one full import if you start fresh and one import which basically checks every 24 hours if updated data is available since the last import and imports it. 

In this case the second process did not work properly due to API changes. This is fixed and with the update the process starts to update the data again, starting from the last proper import date, which is for most a couple days ago. In this process though there seems to be some problem, where the sum of all missing data is set to midnight for each missing day.

The problem is, once fixed with a reset and fully fresh data, it's not reproducible.

**Comment by DarwinsBuddy** [comment] 2024-11-14 22:31
@reox @tschoerk
Could you please test this branch. I don't know if this fixes the issue with the imports, but I suspect that it has something to do with the role being assumed to be the one given in the extra fields of the zaehlpunkt.
Since we switched to bewegungsdaten this might be wrongly passed down to the api call.

I don't know what happens if we query a not quarter-hour opt-in sensor with the role `V002` but I'd like to try it and check if that fixes the issue with the spike.

The reason behind this is, that I tested the "reduction" code for reducing quarter hourly to hourly data with supplying it messwerte queried with a role `V001` and it showed the same behaviour as described in the issue(s).

If someone has a not-opted in sensor (i.e. measuring hourly, not quarter-hourly I'd really appreciate feedback) 

see #275

**Comment by DarwinsBuddy** [comment] 2024-11-15 11:51
I decided to remove the code for reducing everything to one hour splices alongside a warning for importing qh datapoints. @reox @tschoerk please let me know what you think.

**Comment by tschoerk** [comment] 2024-11-15 14:52
> @reox @tschoerk Could you please test this branch. I don't know if this fixes the issue with the imports, but I suspect that it has something to do with the role being assumed to be the one given in the extra fields of the zaehlpunkt. Since we switched to bewegungsdaten this might be wrongly passed down to the api call.
> 
> I don't know what happens if we query a not quarter-hour opt-in sensor with the role `V002` but I'd like to try it and check if that fixes the issue with the spike.
> 
> The reason behind this is, that I tested the "reduction" code for reducing quarter hourly to hourly data with supplying it messwerte queried with a role `V001` and it showed the same behaviour as described in the issue(s).
> 
> If someone has a not-opted in sensor (i.e. measuring hourly, not quarter-hourly I'd really appreciate feedback)
> 
> see #275

With V001 you get only one value per day, so the reduction code basically returns an array with one timestamp each day, so then it looks like a big spike. In all the pictures above, there are still values in the other hours.
I guess the API call even with no opting-in is still V002 and it returns hourly values, but that's only speculation.

> I decided to remove the code for reducing everything to one hour splices alongside a warning for importing qh datapoints. @reox @tschoerk please let me know what you think.

Home assistant will throw an Invalid timestamp error, since in the long-term statistic, it only saves 24 data points each day, so minute and second must be zero (see also https://data.home-assistant.io/docs/statistics).

**Comment by tschoerk** [comment] 2024-11-15 14:53
But I think I figured out what the problem is. The API values are just returning fine, no spikes or anything and the reduction is also working as it should. The problem is that the update of _import_statistics is designed for 24 hour updates and not for more. So what happens if the last update is longer than 24 hours ago, for example 72 hours, so 3 days?

https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/blob/e343eaae81dc1001af69e641ee467feb0f01b353/custom_components/wnsm/statistics_sensor.py#L279-L284

This loop starts with a start date of 72 hours ago and calls bewegungsdaten for the last 72 hours, so 72 entry points (we ignore that the current day has no data yet). Then it adds 24 hours to the old starting point, to make it the new starting point.

For the sum, which each statistic entry has, each of the 72 values is added to the total_usage (total_usage is a running sum - when starting the update it is taken from the last valid statistic entry):
https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/blob/e343eaae81dc1001af69e641ee467feb0f01b353/custom_components/wnsm/statistics_sensor.py#L333

Which then is appened to the statistic:
https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/blob/e343eaae81dc1001af69e641ee467feb0f01b353/custom_components/wnsm/statistics_sensor.py#L338

Now the loop runs again, since the starting point is still before now, since it was only moved 24 hours into the future and not the full 72, BUT the total_usage is already the sum of all 72 new data points. Now the problem starts, since in the second go around the last 48 data points are added again to the total_usage and then in the last round 24. So the sum in the statistics have a jump each day. 

What home assistant shows in the energy dashboard is not the single data point, but the difference of the sum of each sequential data point. That's why there are massive jumps each day, because it's the sum of all the days before it.

**Comment by reox** [comment] 2024-11-15 15:21
good catch! I guess the issue is that previously the API would always return a maximum of 24h, which is no longer the case?

**Comment by W-M-B** [comment] 2024-11-15 15:39
Is there a place where the api by Wiener Netze is explained? like swagger or so, my python skills are very limited ? Maybe

**Comment by reox** [comment] 2024-11-15 18:15
> Yeah it seems so, at least the description of the old verbrauch function says so: `This returns hourly or quarter hour consumptions for a single day, i.e., for 24 hours after the given date_from.`


yep, that's what I have written :) Seems like it's not valid anymore...

> Is there a place where the api by Wiener Netze is explained? 

Nope, it is all trial and error :( I thought about asking Wiener Netze if they would give us a full documentation and support the development of the extension, but that includes the possibility that they simply switch off access completely... Would be interested if someone knows someone from WN who is in charge of this and would not mind having a chat about it.

**Comment by W-M-B** [comment] 2024-11-15 18:34
hi, I have contacts with Wiener Netze, so far I did not reach out to avoid the possibility of them closing the api for externals...
but if you agree, I can reach out and try to get some Austrian way in .. (maybe not formal documentation but something in between).
let me know what you guys think

**Comment by reox** [comment] 2024-11-15 19:06
I'm really unsure what to do. On the one hand side there is a chance that this extensions gets way better - on the other hand there is the chance it gets unusable... I do not really want to decide that :D

**Comment by W-M-B** [comment] 2024-11-15 19:32
maybe you can briefly explain how we use the API at the moment, how public available the api really is. this will help to asses the outcome

**Comment by W-M-B** [comment] 2024-11-15 20:37
very good news @reox .
Wiener Stadtwerke have an API portal where it is free to register.
once registered you can browse through their catalogue.

and no need to guess what I found
(not sure if  the link works) but the smartmeter api is there.
have a look
https://api-portal.wienerstadtwerke.at/portal/apis/7f8a1cce-2a7e-4b18-840b-b0387ed9a3fc/apiinfo

**Comment by DarwinsBuddy** [comment] 2024-11-16 10:49
I can shed some light on all of this.

I had already some discussion with WienerNetze about all of this and they worked extensively on this portal.
I already registered the app there and got coincidentally a couple of days ago a confirmation.
 
Unfortunately, I did not manage to authenticate with my own credentials via jwt s.t. I do not expose any credentials that are app related. Since I do not want to invest into a proxy infrastructure and manage that, I fear that this is a dead end (unless I'm missing some information w.r.t. authentication).

I'd see this unrelated to the problem at hand in this issue, but still would like to keep the discussion, so how about moving this to another issue: #276

**Comment by DarwinsBuddy** [comment] 2024-11-16 10:58
Moving on with this

> But I think I figured out what the problem is. The API values are just returning fine, no spikes or anything and the reduction is also working as it should. The problem is that the update of _import_statistics is designed for 24 hour updates and not for more. So what happens if the last update is longer than 24 hours ago, for example 72 hours, so 3 days?
> 
> https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/blob/e343eaae81dc1001af69e641ee467feb0f01b353/custom_components/wnsm/statistics_sensor.py#L279-L284
> 
> This loop starts with a start date of 72 hours ago and calls bewegungsdaten for the last 72 hours, so 72 entry points (we ignore that the current day has no data yet). Then it adds 24 hours to the old starting point, to make it the new starting point.
> 
> For the sum, which each statistic entry has, each of the 72 values is added to the total_usage (total_usage is a running sum - when starting the update it is taken from the last valid statistic entry):
> 
> https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/blob/e343eaae81dc1001af69e641ee467feb0f01b353/custom_components/wnsm/statistics_sensor.py#L333
> 
> Which then is appened to the statistic:
> 
> https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/blob/e343eaae81dc1001af69e641ee467feb0f01b353/custom_components/wnsm/statistics_sensor.py#L338
> 
> Now the loop runs again, since the starting point is still before now, since it was only moved 24 hours into the future and not the full 72, BUT the total_usage is already the sum of all 72 new data points. Now the problem starts, since in the second go around the last 48 data points are added again to the total_usage and then in the last round 24. So the sum in the statistics have a jump each day.
> 
> What home assistant shows in the energy dashboard is not the single data point, but the difference of the sum of each sequential data point. That's why there are massive jumps each day, because it's the sum of all the days before it.
> 
> So maybe there's no need to even have this loop or if the 24 hour batches make sense, then the call to bewegungsdaten also needs to have an end date.

I got it. I'll try to come up with a fix for this, since `/bewegungsdaten` offers a way to query all the data that was missed at once. Bear with me

**Comment by DarwinsBuddy** [comment] 2024-11-16 12:38
alright. I cleaned up and refactored that part. I'd :heart: some feedback.

**Closed** 2024-11-17 12:25 UTC
Labels: bug, bugfix, API

**Comment by W-M-B** [comment] 2024-11-17 15:00
> deve

hello,
can you explain briefly which sensor and what datarange you delete? thanks!
