### ISSUE TITLE
Protokollfehler - Please file an issue with this error  immer um 22:00

### ISSUE THREAD

**Issue by TomFeix** [DarwinsBuddy/WienerNetzeSmartmeter#240] opened 2024-07-09 21:30 UTC
Logger: custom_components.wnsm.live_sensor
Quelle: custom_components/wnsm/live_sensor.py:68
Integration: WienerNetzeSmartmeter ([Dokumentation](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter), [Probleme](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues))
Erstmals aufgetreten: 1. Juli 2024 um 21:45:26 (194 Vorkommnisse)
Zuletzt protokolliert: 22:45:29

Please file an issue with this error and (anonymized) payload in github {'hasSmartMeter': True, 'isDataDeleted': False, 'zaehlpunkt': 'AT00100000000000000010000150xxxxx', 'type': 'TAGSTROM', 'address': 'xxxxxx(Haus 4), 0000 Wien', 'zip': '0000'} {'consumptionDayBeforeYesterdayValue': 249, 'consumptionDayBeforeYesterdayValidated': True, 'consumptionDayBeforeYesterdayTimestamp': '2024-07-05T22:00:00.000Z'} {'lastValue': 7419452, 'lastReading': '2024-07-07T22:00:00.000Z', 'lastValidated': True, 'lastType': '1-2:1.8.0'} {'optIn': True, 'consumptionAverage': 0, 'consumptionMinimum': 0, 'consumptionMaximum': 0}

**Comment by DarwinsBuddy** [comment] 2024-07-12 08:00
@tschoerk I guess this is related to #233
But could this be fixed with #236 already as well?

**Comment by DarwinsBuddy** [comment] 2024-07-12 08:02
Duplicate of #227

**Comment by TomFeix** [comment] 2024-07-12 22:36
Sorry I have one customerID one Smartmeter 2 Zählpunkte  get only "Verbrauch" - "Einspeisung" missing - last Version 
ist there a configuration sample in the yaml (find only for 1 Zählpunkt)
sorry all the items are confusing - should i Reinstall - only deinstall and install ore delete all entries
pls help

**Comment by TomFeix** [comment] 2024-07-12 23:41
So i deinstalled deleted statistic - reinstalled get only 3 entries 
1. has data  2. ok no data  3. ? also no data is for Einspeisung

![image](https://github.com/user-attachments/assets/89a299e9-757a-41a1-a148-fc7add393819)

**Comment by TomFeix** [comment] 2024-07-17 20:56
> @tschoerk I guess this is related to #233 But could this be fixed with #236 already as well?

does not function!

**Comment by TomFeix** [comment] 2024-07-17 20:57
> Duplicate of #227

does not function

**Comment by tschoerk** [comment] 2024-07-18 07:16
I would try the following steps, which resets everything completely and imports it again (see #19 How can I start over with a fresh data import?):
1. Navigate to the energy configuration and remove the sensors for consumption and feed-in
![grafik](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/16376109/dfcac803-47cd-4bbe-ace9-c3ce32c17885)
2. Remove the statistical data of the sensors
    - Navigate to Developer tools -> Services -> Recorder: Clean up entities
    - Select all sensors (start with AT001)
    - Deactivate `Domains to remove` and `Entity globs to remove`
    - Select `Days to keep` and select 0
    - Click on `Execute service`
![grafik](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/16376109/7780a776-5c6e-4cf5-8c5d-bb40545d10ea)
3. Remove the integration
    - Navigate to [Integrationen](https://my.home-assistant.io/redirect/integrations/) and to the entry of `WienerNetzeSmartmeter`.
    - Select the 3 points for ALL entries and click `Delete`
![grafik](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/16376109/a6786f46-1011-4220-93ab-75800590967e)
4. Navigate to Developer tools -> [Statistics](https://my.home-assistant.io/redirect/developer_statistics/)
    - Enter AT001 in the search above
    - For each entry, a button should appear on the right “Problems with this integration”
    - Click on it and select delete
5. Reboot HomeAssistant
6. Install the newest version with HACS
7. Reboot HomeAssistant
8. Add the integration `WienerNetzeSmartmeter` again

Now 4 entities should be found, two “normal” and two “statistics”. In the energy configuration, the statistics sensors can now be added again for consumption and feed-in so that everything is clearly visible on the energy dashboard.

If the problems still occur, a good starting point for identifying problems is to activate debug logging in the integration:
1. delete the entities in the integration
2. activate the debug logging
3. add the entities again using Add entry
4. deactivate the debug logging - a log should be downloaded automatically
5. post the relevant parts, i.e. error messages etc. here
![wnsm_integration](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/16376109/9920f115-1f31-4db1-8ef0-776b92617f5e)

**Comment by DarwinsBuddy** [comment] 2024-10-26 14:12
@TomFeix does your problem still exist?

@tschoerk Thank you so much for adding so much detail to the troubleshooting steps. I edited our [FAQs](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/discussions/19) to match your description. :heart:

**Comment by TomFeix** [comment] 2024-10-26 17:14
Wow top
Ing. Thomas Feix
+43 664 1004311


Am 26.10.2024 um 16:13 schrieb Christoph Spörk ***@***.***>:

﻿

@TomFeix<https://github.com/TomFeix> does your problem still exist?

@tschoerk<https://github.com/tschoerk> Thank you so much for adding so much detail to the troubleshooting steps. I edited our FAQs<https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/discussions/19> to match your description. ❤️

**Comment by franz-josef-kaiser** [comment] 2024-10-26 18:52
@TomFeix you might want to remove your comment, containing personal identifiable information (prob. from your mail footer).

**Comment by TomFeix** [comment] 2024-10-26 20:05
> @TomFeix you might want to remove your comment, containing personal identifiable information (prob. from your mail footer).

many thanks

**Closed** 2024-10-28 08:10 UTC
