### ISSUE TITLE
Prices with 1h consumption

### ISSUE THREAD

**Issue by webwude** [DarwinsBuddy/WienerNetzeSmartmeter#266] opened 2024-10-25 13:35 UTC
Hi.

I currently use the integration with the statistics sensor feeding yesterday's consumption. 
In addition I use a dynamic price provider which is included as sensor as well.

With my old setup (ir adapter) I got the costs as well.
Now with the integration costs are 0. Is there any chance to get the costs somehow?

**Comment by reox** [comment] 2024-10-25 16:14
I believe they are not transmitted via the API. Is this something you can see in the WN Smart Meter Dashboard? If so, than you could try to reverse engineer which API endpoint to use.

**Comment by webwude** [comment] 2024-10-25 16:55
The price is a separate integration. It is based on Epex Spot prices.

**Comment by reox** [comment] 2024-10-25 17:06
ah okay - I think then the issue is that this only imports statistics, where as the other integration probably requires actual values? I believe there is nothing we can do, as the API transmits values with a delay of at least 24h.

**Comment by webwude** [comment] 2024-10-26 06:38
Ok. Thx anyway.

**Comment by DarwinsBuddy** [comment] 2024-10-26 14:02
closing this for now. If we once get something like a public API from Wiener Netze maybe this could be a valid feature request. :)

**Closed by DarwinsBuddy** 2024-10-26 14:02 UTC

**Comment by Constipated-Monk** [comment] 2024-12-08 12:11
coming back to this, with the new API integration and the new sensor in the new WNSM version, is it possible to get this functionality working? 
in HA under energy setttings "use an entity with current price" is greyed out. EPEX Spot gives hourly prices and the WNSM sensor should also have data on hourly basis. so they should match and connect rather easily?
