### ISSUE TITLE
two Smartmeters under the same contract. consumption and production

### ISSUE THREAD

**Issue by GeraldPape** [DarwinsBuddy/WienerNetzeSmartmeter#230] opened 2024-05-14 07:56 UTC
I see both smartmeters in my config, but the second one never has any values.
Any hints how to fix, or what do you need to analyze?

_Originally posted by @GeraldPape in https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/discussions/19#discussioncomment-9093639_

**Comment by tschoerk** [comment] 2024-05-21 19:53
Fix for second statistic sensor: #228 
Fix for second live sensor: #233

**Comment by DarwinsBuddy** [comment] 2024-07-12 08:06
@tschoerk #228 I merged, but for #233 I'd like to understand the possible race condition a bit more

**Comment by DarwinsBuddy** [comment] 2024-07-12 08:11
let's move this to #227 

Duplicate of #227

**Closed by DarwinsBuddy** 2024-07-12 08:11 UTC
